# coding: utf-8

"""
    Synapse DB

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.4.1
    Generated by: https://openapi-generator.tech
"""

from petstore_api.paths.user_auth_database_login.post import AuthDatabaseLoginUserAuthDatabaseLoginPost
from petstore_api.paths.user_auth_database_logout.post import AuthDatabaseLogoutUserAuthDatabaseLogoutPost
from petstore_api.paths.user_auth_jwt_login.post import AuthJwtLoginUserAuthJwtLoginPost
from petstore_api.paths.user_auth_jwt_logout.post import AuthJwtLogoutUserAuthJwtLogoutPost


class AuthApi(
    AuthDatabaseLoginUserAuthDatabaseLoginPost,
    AuthDatabaseLogoutUserAuthDatabaseLogoutPost,
    AuthJwtLoginUserAuthJwtLoginPost,
    AuthJwtLogoutUserAuthJwtLogoutPost,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
