# coding: utf-8

"""
    Synapse DB

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.4.1
    Generated by: https://openapi-generator.tech
"""

from petstore_api.paths.stargate_neurodata_dataset_my_datasets.get import UserDatasetsStargateNeurodataDatasetMyDatasetsGet
from petstore_api.paths.stargate_neurodata_dataset_my_projects.get import UserProjectsStargateNeurodataDatasetMyProjectsGet


class DataApi(
    UserDatasetsStargateNeurodataDatasetMyDatasetsGet,
    UserProjectsStargateNeurodataDatasetMyProjectsGet,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
