# coding: utf-8

"""
    Synapse DB

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.4.1
    Generated by: https://openapi-generator.tech
"""

from petstore_api.paths.stargate_neurodata_stargate_jwks_json.get import JwksStargateNeurodataStargateJwksJsonGet
from petstore_api.paths.stargate_neurodata_stargate_read_neuro_data_json.get import ReadNeuroDataStargateNeurodataStargateReadNeuroDataJsonGet
from petstore_api.paths.stargate_neurodata_stargate_upload_existing_dataset_id.get import UploadExistingDatasetStargateNeurodataStargateUploadExistingDatasetIdGet
from petstore_api.paths.stargate_neurodata_stargate_upload_new.post import UploadNewDatasetStargateNeurodataStargateUploadNewPost
from petstore_api.paths.stargate_neurodata_dataset_my_datasets.get import UserDatasetsStargateNeurodataDatasetMyDatasetsGet
from petstore_api.paths.stargate_neurodata_dataset_my_projects.get import UserProjectsStargateNeurodataDatasetMyProjectsGet


class StargateApi(
    JwksStargateNeurodataStargateJwksJsonGet,
    ReadNeuroDataStargateNeurodataStargateReadNeuroDataJsonGet,
    UploadExistingDatasetStargateNeurodataStargateUploadExistingDatasetIdGet,
    UploadNewDatasetStargateNeurodataStargateUploadNewPost,
    UserDatasetsStargateNeurodataDatasetMyDatasetsGet,
    UserProjectsStargateNeurodataDatasetMyProjectsGet,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
