# coding: utf-8

"""
    Synapse DB

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.4.1
    Generated by: https://openapi-generator.tech
"""

from petstore_api.paths.user_auth_database_login.post import AuthDatabaseLoginUserAuthDatabaseLoginPost
from petstore_api.paths.user_auth_database_logout.post import AuthDatabaseLogoutUserAuthDatabaseLogoutPost
from petstore_api.paths.user_auth_jwt_login.post import AuthJwtLoginUserAuthJwtLoginPost
from petstore_api.paths.user_auth_jwt_logout.post import AuthJwtLogoutUserAuthJwtLogoutPost
from petstore_api.paths.user_register.post import RegisterRegisterUserRegisterPost
from petstore_api.paths.user_profile_json.get import UserProfileUserProfileJsonGet
from petstore_api.paths.user_request_verify_token.post import VerifyRequestTokenUserRequestVerifyTokenPost
from petstore_api.paths.user_verify.post import VerifyVerifyUserVerifyPost


class UserApi(
    AuthDatabaseLoginUserAuthDatabaseLoginPost,
    AuthDatabaseLogoutUserAuthDatabaseLogoutPost,
    AuthJwtLoginUserAuthJwtLoginPost,
    AuthJwtLogoutUserAuthJwtLogoutPost,
    RegisterRegisterUserRegisterPost,
    UserProfileUserProfileJsonGet,
    VerifyRequestTokenUserRequestVerifyTokenPost,
    VerifyVerifyUserVerifyPost,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
