# coding: utf-8

"""
    Synapse DB

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.4.1
    Generated by: https://openapi-generator.tech
"""

import unittest

import petstore_api
from petstore_api.model.http_validation_error import HTTPValidationError
from petstore_api import configuration


class TestHTTPValidationError(unittest.TestCase):
    """HTTPValidationError unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
