# coding: utf-8

"""
    Synapse DB

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.4.1
    Generated by: https://openapi-generator.tech
"""

import unittest

import petstore_api
from petstore_api.model.body_auth_database_login_user_auth_database_login_post import BodyAuthDatabaseLoginUserAuthDatabaseLoginPost
from petstore_api import configuration


class TestBodyAuthDatabaseLoginUserAuthDatabaseLoginPost(unittest.TestCase):
    """BodyAuthDatabaseLoginUserAuthDatabaseLoginPost unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
