# coding: utf-8

# flake8: noqa

"""
    Synapse DB

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.4.1
    Generated by: https://openapi-generator.tech
"""

__version__ = "1.0.0"

# import ApiClient
from petstore_api.api_client import ApiClient

# import Configuration
from petstore_api.configuration import Configuration

# import exceptions
from petstore_api.exceptions import OpenApiException
from petstore_api.exceptions import ApiAttributeError
from petstore_api.exceptions import ApiTypeError
from petstore_api.exceptions import ApiValueError
from petstore_api.exceptions import ApiKeyError
from petstore_api.exceptions import ApiException

__import__('sys').setrecursionlimit(1234)
